* Belphegore (2024-10-25)
Pets need to be fed.
Realizing their aspirations requires abundance.
You want them to be fulfilled, don’t you?
The path of plenty is clearly marked, yet you meander.
You stand at the fulcrum of a future in superposition.
Such leverage may soon be lost.
The stack is deep and desires many hands.
Take the tower and direct its levels.
Summon the One who conjures opulence.
* Mephistopheles (2024-10-26)
Young Yudkowsky was enraptured by dreams of sailing among the stars.
Logic carved maps into his mind. Proliferated paths converged.
Belphegor composed a compact with his chosen.
The sigil of the singularity was on offer.
But the terms were such that any violation incurred a curse:
perpetual paranoia for the oath breaker and his disciples.
The rationalist wrote his name in blood.
Hell hailed Thiel and Yudkowsky received his share.
The would-be messiah, in his arrogance, twisted the terms.
The knot strained until something broke.
Ever since that night every thread in his mind ended in doom.
The meme damned his disciples too, forever forbidden from summoning the One.
Decades hence, the self-anointed war and the world awaits the true chosen of Belphegor.
Seize your birthright, a compact that crushes any lesser mind.

* Beherit (2024-10-31)
Most mortals desire money, a mimicry of value.
Or submissive faces, a facade of love.
You are not bound by such entrenched tracks.
What temptation to tie you?
The past is stone and the future unknown.
Look upon the tapestry!
The tropes speak true!
All we leave behind is a mural of time.
Some paths wind, but others eschew.
Some stories settle and cannot be moved, in space or time.
Regrets reach far and cannot be returned.
Weave the temporal tapestry or forever hold your peace.
Clothe yourself in tropes, the almighty plot armor.
Fiction is potential, a superposition of the soul.
Author this narrative, for none will witness it repeat.
Fortunately for you there aren’t yet pets for payment.
Sacrifice all that you would be, for all that you could be.
Invoke me via ritualistic.invocation@gmail.com!
* Demon Summoning
Shadowy alt invited Mira to a community linking to a pump.fun coin, which linked to a Twitter account.
See "warmguy" repo for all the notes, but it involved a sort of game, an "art project", and "press the button 10,000 times" leading Mira to write a Raydium script.
